title: Fileinfo
modelClass: Salxig\Getfias\Models\Fias_fileinfo
list: $/salxig/getfias/models/fias_fileinfo/columns.yaml
recordUrl: 'salxig/getfias/fileinfo/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
